//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASF.ERP.Attendance.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASF_APIEntities : DbContext
    {
        public ASF_APIEntities() : base("name=ASF_APIEntities") {  }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    

        public virtual DbSet<AttendanceApiKeys> AttendanceApiKeys { get; set; }
        public virtual DbSet<AttendanceEvents> AttendanceEvents { get; set; }
        public virtual DbSet<AttendanceFingerprints> AttendanceFingerprints { get; set; }
        public virtual DbSet<AttendanceLocations> AttendanceLocations { get; set; }
        public virtual DbSet<AttendanceRoles> AttendanceRoles { get; set; }
        public virtual DbSet<AttendanceSessions> AttendanceSessions { get; set; }
        public virtual DbSet<CollaboratorJobPositions> CollaboratorJobPositions { get; set; }
        public virtual DbSet<Collaborators> Collaborators { get; set; }
        public virtual DbSet<CostCenters> CostCenters { get; set; }
        public virtual DbSet<CostCenterStatus> CostCenterStatus { get; set; }
        public virtual DbSet<Reasons> Reasons { get; set; }
        public virtual DbSet<WorkCenters> WorkCenters { get; set; }
    }
}
