//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASF.ERP.Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceEvents
    {
        public int EventId { get; set; }
        public int SessionId { get; set; }
        public int CollaboratorId { get; set; }
        public int CostCenterId { get; set; }
        public System.DateTime Datetime { get; set; }
    
        public virtual AttendanceSessions AttendanceSessions { get; set; }
        public virtual Collaborators Collaborators { get; set; }
        public virtual CostCenters CostCenters { get; set; }
    }
}
