//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASF.ERP.Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceFingerprints
    {
        public int FingerprintId { get; set; }
        public int CollaboratorId { get; set; }
        public int RoleId { get; set; }
        public string Fingerprint { get; set; }
    
        public virtual AttendanceRoles AttendanceRoles { get; set; }
        public virtual Collaborators Collaborators { get; set; }
    }
}
