//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASF.ERP.Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collaborators
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Collaborators()
        {
            this.AttendanceEvents = new HashSet<AttendanceEvents>();
            this.AttendanceFingerprints = new HashSet<AttendanceFingerprints>();
            this.AttendanceSessions = new HashSet<AttendanceSessions>();
        }
    
        public int CollaboratorId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Lastname2 { get; set; }
        public string EMail { get; set; }
        public Nullable<int> Tag { get; set; }
        public Nullable<int> CoordinatorLocationId { get; set; }
        public Nullable<short> CollaboratorJobPositionId { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public string NSS { get; set; }
        public string CURP { get; set; }
        public string BACcount { get; set; }
        public Nullable<int> ResidenceId { get; set; }
        public string RFC { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Proof { get; set; }
        public Nullable<int> IdEvent { get; set; }
        public string CreditNumber { get; set; }
        public Nullable<decimal> DiscountFactor { get; set; }
        public Nullable<int> DiscountTypeId { get; set; }
        public Nullable<bool> ApplyInfonavitData { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<System.DateTime> RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceEvents> AttendanceEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceFingerprints> AttendanceFingerprints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceSessions> AttendanceSessions { get; set; }
        public virtual CollaboratorJobPositions CollaboratorJobPositions { get; set; }
    }
}
