//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASF.ERP.Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CostCenters()
        {
            this.AttendanceEvents = new HashSet<AttendanceEvents>();
        }
    
        public int CostCenterId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int WorkCenterId { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public byte CostCenterStatusId { get; set; }
        public Nullable<bool> ContainsSensitiveInformation { get; set; }
        public Nullable<bool> IsGeneric { get; set; }
        public Nullable<bool> AllowManualRequisitions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceEvents> AttendanceEvents { get; set; }
        public virtual CostCenterStatus CostCenterStatus { get; set; }
        public virtual WorkCenters WorkCenters { get; set; }
    }
}
