//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASF.ERP.Attendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkCenters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkCenters()
        {
            this.CostCenters = new HashSet<CostCenters>();
        }
    
        public int WorkCenterId { get; set; }
        public string Name { get; set; }
        public string Site { get; set; }
        public Nullable<int> ReasonId { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<bool> SeeAllCostCenters { get; set; }
        public Nullable<decimal> FIS { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual AttendanceLocations AttendanceLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostCenters> CostCenters { get; set; }
        public virtual Reasons Reasons { get; set; }
    }
}
